version: '3.7'

services:
  app:
    container_name: wesgur.github.io
    build:
      context: .    
    volumes:
      - .:/app
      - node_modules:/app/node_modules/

    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true      
    expose:
      - ${APP_PORT}

volumes:
  node_modules: